/*

undefined
Remote request schema, e.g. how TSP should call MaaS-backend

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';

export const schemaId =
  'http://maasglobal.com/tsp/webhooks-bookings-update/remote-request.json';

// Success
