/*

undefined
Response schema for tsp-auth validate

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'maas-schemas-ts/core/components/common';

export const schemaId =
  'http://maasglobal.com/maas-backend/tsp-auth/validate/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    location?: Common_.WhimDeepLink;
  } & {
    location: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      location: Common_.WhimDeepLink,
    }),
    t.type({
      location: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      location?: Common_.WhimDeepLink;
    } & {
      location:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
