/*

undefined
MaaS customer schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as PersonalData_ from 'src/maas-backend/customers/personalData';
import * as PaymentSource_ from 'src/maas-backend/customers/payment-sources/paymentSource';
import * as Fare_ from 'src/core/components/fare';
import * as Region_ from 'src/core/region';
import * as Authorization_ from 'src/core/components/authorization';

export const schemaId = 'http://maasglobal.com/maas-backend/customers/customer.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    profileImageUrl?: string;
    personalData?: PersonalData_.Default;
    paymentSources?: Array<PaymentSource_.PaymentSource>;
    balances?: Array<Fare_.Default>;
    region?: Region_.Default;
    authorizations?: Array<Authorization_.Default>;
  } & {
    personalData: unknown;
    paymentSources: unknown;
    balances: unknown;
    region: unknown;
    authorizations: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      profileImageUrl: t.string,
      personalData: PersonalData_.Default,
      paymentSources: t.array(PaymentSource_.PaymentSource),
      balances: t.array(Fare_.Default),
      region: Region_.Default,
      authorizations: t.array(Authorization_.Default),
    }),
    t.type({
      personalData: t.unknown,
      paymentSources: t.unknown,
      balances: t.unknown,
      region: t.unknown,
      authorizations: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      profileImageUrl?: string;
      personalData?: PersonalData_.Default;
      paymentSources?: Array<PaymentSource_.PaymentSource>;
      balances?: Array<Fare_.Default>;
      region?: Region_.Default;
      authorizations?: Array<Authorization_.Default>;
    } & {
      personalData: unknown;
      paymentSources: unknown;
      balances: unknown;
      region: unknown;
      authorizations: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
