/*

undefined
Response schema for autocomplete

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/autocomplete/autocomplete-query/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    suggestions?: Array<string>;
    debug?: {};
  } & {
    suggestions: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      suggestions: t.array(t.string),
      debug: t.type({}),
    }),
    t.type({
      suggestions: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      suggestions?: Array<string>;
      debug?: {};
    } & {
      suggestions: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
