/*

undefined
Request schema for profile-active-plan-put

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as ApiCommon_ from 'maas-schemas-ts/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/profile/profile-devices-put/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    payload?: {
      devicePushToken?: string;
      deviceIdentifier?: Units_.Uuid;
      deviceType?: string & ('iOS' | 'Android');
    } & {
      devicePushToken: {} | null;
      deviceIdentifier: {} | null;
      deviceType: {} | null;
    };
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    identityId: Units_.IdentityId,
    payload: t.intersection([
      t.partial({
        devicePushToken: t.string,
        deviceIdentifier: Units_.Uuid,
        deviceType: t.intersection([
          t.string,
          t.union([t.literal('iOS'), t.literal('Android')]),
        ]),
      }),
      t.type({
        devicePushToken: t.union([t.type({}), t.null]),
        deviceIdentifier: t.union([t.type({}), t.null]),
        deviceType: t.union([t.type({}), t.null]),
      }),
    ]),
    headers: ApiCommon_.Headers,
  }),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      payload?: {
        devicePushToken?: string;
        deviceIdentifier?: Units_.Uuid;
        deviceType?: string & ('iOS' | 'Android');
      } & {
        devicePushToken: {} | null;
        deviceIdentifier: {} | null;
        deviceType: {} | null;
      };
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
