/*

undefined
Request schema for profile-active-plan-put

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/profile/profile-devices-put/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    payload?: {
      devicePushToken: string;
      deviceIdentifier: Units_.Uuid;
      deviceType: string;
    };
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.exact(
    t.partial({
      identityId: Units_.IdentityId,
      payload: t.exact(
        t.type({
          devicePushToken: t.string,
          deviceIdentifier: Units_.Uuid,
          deviceType: t.string,
        }),
      ),
      headers: ApiCommon_.Headers,
    }),
  ),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      payload?: {
        devicePushToken: string;
        deviceIdentifier: Units_.Uuid;
        deviceType: string;
      };
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
