/*

undefined
Response schema for booking-option-create

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'maas-schemas-ts/core/booking';

export const schemaId =
  'http://maasglobal.com/maas-backend/booking-option-create/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  | ({
      booking?: Booking_.Default;
    } & {
      booking: {} | null;
    })
  | ({
      error?: {
        message?: string;
      };
    } & {
      error: {} | null;
    }),
  DefaultBrand
>;
export const Default = t.brand(
  t.union([
    t.intersection([
      t.partial({
        booking: Booking_.Default,
      }),
      t.type({
        booking: t.union([t.type({}), t.null]),
      }),
    ]),
    t.intersection([
      t.partial({
        error: t.partial({
          message: t.string,
        }),
      }),
      t.type({
        error: t.union([t.type({}), t.null]),
      }),
    ]),
  ]),
  (
    x,
  ): x is t.Branded<
    | ({
        booking?: Booking_.Default;
      } & {
        booking: {} | null;
      })
    | ({
        error?: {
          message?: string;
        };
      } & {
        error: {} | null;
      }),
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
