/*

undefined
Response schema for getting a receipt for specific booking

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/tsp/bookings-receipt/response.json';

// Success
