/*

undefined
MaaS customer stats. Give lifetime stats of customer e.g total number of bookings and itineraries

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/stats/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    lifetimeBookingsCount?: number;
    lifetimeItinerariesCount?: number;
    profileCreationTimestamp?: Units_.Time;
  } & {
    identityId: unknown;
    lifetimeBookingsCount: unknown;
    lifetimeItinerariesCount: unknown;
    profileCreationTimestamp: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      lifetimeBookingsCount: t.number,
      lifetimeItinerariesCount: t.number,
      profileCreationTimestamp: Units_.Time,
    }),
    t.type({
      identityId: t.unknown,
      lifetimeBookingsCount: t.unknown,
      lifetimeItinerariesCount: t.unknown,
      profileCreationTimestamp: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      lifetimeBookingsCount?: number;
      lifetimeItinerariesCount?: number;
      profileCreationTimestamp?: Units_.Time;
    } & {
      identityId: unknown;
      lifetimeBookingsCount: unknown;
      lifetimeItinerariesCount: unknown;
      profileCreationTimestamp: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
