/*

undefined
MaaS customer stats. Give lifetime stats of customer e.g total number of bookings and itineraries

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'maas-schemas-ts/core/components/units';

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/stats/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    lifetimeBookingsCount?: number;
    lifetimeItinerariesCount?: number;
    profileCreationTimestamp?: Units_.Time;
  } & {
    identityId: {} | null;
    lifetimeBookingsCount: {} | null;
    lifetimeItinerariesCount: {} | null;
    profileCreationTimestamp: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      lifetimeBookingsCount: t.number,
      lifetimeItinerariesCount: t.number,
      profileCreationTimestamp: Units_.Time,
    }),
    t.type({
      identityId: t.union([t.type({}), t.null]),
      lifetimeBookingsCount: t.union([t.type({}), t.null]),
      lifetimeItinerariesCount: t.union([t.type({}), t.null]),
      profileCreationTimestamp: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      lifetimeBookingsCount?: number;
      lifetimeItinerariesCount?: number;
      profileCreationTimestamp?: Units_.Time;
    } & {
      identityId: {} | null;
      lifetimeBookingsCount: {} | null;
      lifetimeItinerariesCount: {} | null;
      profileCreationTimestamp: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
