/*

undefined
Response schema for retrieving a ticket from booking through a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/tsp/bookings-ticket/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    ticket: string;
    type: string;
    contentType: string;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    ticket: t.string,
    type: t.string,
    contentType: t.string,
  }),
  (
    x,
  ): x is t.Branded<
    {
      ticket: string;
      type: string;
      contentType: string;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
