/*

undefined
undefined

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_SCOOTER.json';

export type Default = t.Branded<
  {
    scooter?: {
      id: string;
    };
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    scooter: t.type({
      id: t.string,
    }),
  }),
  (
    x,
  ): x is t.Branded<
    {
      scooter?: {
        id: string;
      };
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
