/*

undefined
undefined

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_SHARED_BICYCLE.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    bike?: {
      id?: string;
      type?: string;
    } & {
      id: {} | null;
    };
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    bike: t.intersection([
      t.partial({
        id: t.string,
        type: t.string,
      }),
      t.type({
        id: t.union([t.type({}), t.null]),
      }),
    ]),
  }),
  (
    x,
  ): x is t.Branded<
    {
      bike?: {
        id?: string;
        type?: string;
      } & {
        id: {} | null;
      };
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
