/*

undefined
MaaS customer update

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as PersonalData_ from 'src/maas-backend/customers/personalData';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/update/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    customerId?: Units_.IdentityId;
    payload?: {
      customer?: {
        profileImageUrl?: string;
        personalData?: PersonalData_.Default;
      };
    } & {
      customer: unknown;
    };
    headers?: ApiCommon_.Headers;
  } & {
    identityId: unknown;
    customerId: unknown;
    payload: unknown;
    headers: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      customerId: Units_.IdentityId,
      payload: t.intersection([
        t.partial({
          customer: t.partial({
            profileImageUrl: t.string,
            personalData: PersonalData_.Default,
          }),
        }),
        t.type({
          customer: t.unknown,
        }),
      ]),
      headers: ApiCommon_.Headers,
    }),
    t.type({
      identityId: t.unknown,
      customerId: t.unknown,
      payload: t.unknown,
      headers: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      customerId?: Units_.IdentityId;
      payload?: {
        customer?: {
          profileImageUrl?: string;
          personalData?: PersonalData_.Default;
        };
      } & {
        customer: unknown;
      };
      headers?: ApiCommon_.Headers;
    } & {
      identityId: unknown;
      customerId: unknown;
      payload: unknown;
      headers: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
