/*

undefined
Response schema for completing customer authorization for TSP

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as Error_ from 'maas-schemas-ts/core/error';

export const schemaId = 'http://maasglobal.com/tsp/customer-auth-validate/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    authToken?: Common_.EncodedQueryParam;
    validTo?: Units_.Time;
    nonce?: Common_.EncodedQueryParam;
    error?: Error_.Default;
  } & (
    | {
        authToken:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
        nonce:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
        validTo:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
      }
    | {
        error:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
        nonce:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
      }),
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      authToken: Common_.EncodedQueryParam,
      validTo: Units_.Time,
      nonce: Common_.EncodedQueryParam,
      error: Error_.Default,
    }),
    t.union([
      t.type({
        authToken: t.union([
          t.UnknownRecord,
          t.UnknownArray,
          t.string,
          t.boolean,
          t.number,
          t.null,
        ]),
        nonce: t.union([
          t.UnknownRecord,
          t.UnknownArray,
          t.string,
          t.boolean,
          t.number,
          t.null,
        ]),
        validTo: t.union([
          t.UnknownRecord,
          t.UnknownArray,
          t.string,
          t.boolean,
          t.number,
          t.null,
        ]),
      }),
      t.type({
        error: t.union([
          t.UnknownRecord,
          t.UnknownArray,
          t.string,
          t.boolean,
          t.number,
          t.null,
        ]),
        nonce: t.union([
          t.UnknownRecord,
          t.UnknownArray,
          t.string,
          t.boolean,
          t.number,
          t.null,
        ]),
      }),
    ]),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      authToken?: Common_.EncodedQueryParam;
      validTo?: Units_.Time;
      nonce?: Common_.EncodedQueryParam;
      error?: Error_.Default;
    } & (
      | {
          authToken:
            | Record<string, unknown>
            | Array<unknown>
            | string
            | boolean
            | number
            | null;
          nonce:
            | Record<string, unknown>
            | Array<unknown>
            | string
            | boolean
            | number
            | null;
          validTo:
            | Record<string, unknown>
            | Array<unknown>
            | string
            | boolean
            | number
            | null;
        }
      | {
          error:
            | Record<string, unknown>
            | Array<unknown>
            | string
            | boolean
            | number
            | null;
          nonce:
            | Record<string, unknown>
            | Array<unknown>
            | string
            | boolean
            | number
            | null;
        }),
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
