/*

undefined
Request schema for subscriptions-customer-retrieve

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as ApiCommon_ from 'maas-schemas-ts/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-customer-retrieve/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    userId?: Units_.IdentityId;
    customerId?: Units_.IdentityId;
    headers?: ApiCommon_.Headers;
  } & {
    customerId: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      userId: Units_.IdentityId,
      customerId: Units_.IdentityId,
      headers: ApiCommon_.Headers,
    }),
    t.type({
      customerId: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      userId?: Units_.IdentityId;
      customerId?: Units_.IdentityId;
      headers?: ApiCommon_.Headers;
    } & {
      customerId: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
