/*

undefined
Request schema for itinerary-cancel

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-cancel/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    itineraryId?: Units_.Uuid;
    headers?: ApiCommon_.Headers;
  } & {
    itineraryId: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      identityId: Units_.IdentityId,
      itineraryId: Units_.Uuid,
      headers: ApiCommon_.Headers,
    }),
    t.type({
      itineraryId: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      itineraryId?: Units_.Uuid;
      headers?: ApiCommon_.Headers;
    } & {
      itineraryId: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
