/*

undefined
Request schema for itinerary-cancel

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-cancel/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    identityId?: Units_.IdentityId;
    itineraryId: Units_.Uuid;
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.exact(
    t.intersection([
      t.type({
        itineraryId: Units_.Uuid,
      }),
      t.partial({
        identityId: Units_.IdentityId,
        headers: ApiCommon_.Headers,
      }),
    ]),
  ),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      itineraryId: Units_.Uuid;
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
