/*

undefined
MaaS.fi geocoding (GeoJSON) response schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Geolocation_ from 'maas-schemas-ts/core/components/geolocation';

export const schemaId =
  'http://maasglobal.com/maas-backend/geocoding/geocoding-query/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    type?: 'FeatureCollection';
    features?: Array<Geolocation_.Feature>;
    debug?: {};
  } & {
    type: {} | null;
    features: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      type: t.literal('FeatureCollection'),
      features: t.array(Geolocation_.Feature),
      debug: t.type({}),
    }),
    t.type({
      type: t.union([t.type({}), t.null]),
      features: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      type?: 'FeatureCollection';
      features?: Array<Geolocation_.Feature>;
      debug?: {};
    } & {
      type: {} | null;
      features: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
