/*

undefined
Request schema for updating user location

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/tracking/tracking-update-user-location/request.json';

// Success
