/*

undefined
MaaS Invoice schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as InvoiceUnits_ from 'maas-schemas-ts/maas-backend/invoices/invoiceUnits';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as InvoiceLineItem_ from 'maas-schemas-ts/maas-backend/invoices/invoiceLineItem';

export const schemaId = 'http://maasglobal.com/maas-backend/invoices/invoice.json';
// Invoice
// The purpose of this remains a mystery
export type Invoice = t.Branded<
  {
    id?: InvoiceUnits_.InvoiceId;
    customerId?: Units_.IdentityId;
    bookingId?: Units_.Uuid;
    lineItems?: Array<InvoiceLineItem_.InvoiceLineItem>;
  } & {
    id: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    customerId:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    bookingId:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    lineItems:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
  },
  InvoiceBrand
>;
export const Invoice = t.brand(
  t.intersection([
    t.partial({
      id: InvoiceUnits_.InvoiceId,
      customerId: Units_.IdentityId,
      bookingId: Units_.Uuid,
      lineItems: t.array(InvoiceLineItem_.InvoiceLineItem),
    }),
    t.type({
      id: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      customerId: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      bookingId: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      lineItems: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id?: InvoiceUnits_.InvoiceId;
      customerId?: Units_.IdentityId;
      bookingId?: Units_.Uuid;
      lineItems?: Array<InvoiceLineItem_.InvoiceLineItem>;
    } & {
      id: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      customerId:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      bookingId:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      lineItems:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
    },
    InvoiceBrand
  > => true,
  'Invoice',
);
export interface InvoiceBrand {
  readonly Invoice: unique symbol;
}
// Default
// The default export. More information at the top.
export type Default = t.Branded<unknown, DefaultBrand>;
export const Default = t.brand(
  t.unknown,
  (x): x is t.Branded<unknown, DefaultBrand> => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
