/*

undefined
Response schema for subscriptions-estimate

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Pricing_ from 'maas-schemas-ts/maas-backend/subscriptions/pricing';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-estimate/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    estimate?: Pricing_.Default;
    immediateUpdate?: boolean;
    debug?: {};
  } & {
    estimate: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      estimate: Pricing_.Default,
      immediateUpdate: t.boolean,
      debug: t.type({}),
    }),
    t.type({
      estimate: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      estimate?: Pricing_.Default;
      immediateUpdate?: boolean;
      debug?: {};
    } & {
      estimate: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
