/*

undefined
Request schema for initiating customer authorization for TSP

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as I18n_ from 'maas-schemas-ts/core/components/i18n';

export const schemaId = 'http://maasglobal.com/tsp/customer-auth/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    nonce?: Common_.EncodedQueryParam;
    returnUrl?: Units_.Url;
    locale?: I18n_.Locale;
  } & {
    nonce: unknown;
    returnUrl: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      nonce: Common_.EncodedQueryParam,
      returnUrl: Units_.Url,
      locale: I18n_.Locale,
    }),
    t.type({
      nonce: t.unknown,
      returnUrl: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      nonce?: Common_.EncodedQueryParam;
      returnUrl?: Units_.Url;
      locale?: I18n_.Locale;
    } & {
      nonce: unknown;
      returnUrl: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
