/*

undefined
Request schema for itinerary-retrieve

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as ApiCommon_ from 'maas-schemas-ts/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-retrieve/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    itineraryId?: Units_.Uuid;
    originalFare?: string;
    headers?: ApiCommon_.Headers;
  } & {
    itineraryId: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      itineraryId: Units_.Uuid,
      originalFare: t.string,
      headers: ApiCommon_.Headers,
    }),
    t.type({
      itineraryId: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      itineraryId?: Units_.Uuid;
      originalFare?: string;
      headers?: ApiCommon_.Headers;
    } & {
      itineraryId: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
