/*

undefined
Response schema for bookings-list

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';

export const schemaId =
  'http://maasglobal.com/maas-backend/bookings/bookings-list/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    bookings?: Array<Booking_.Default>;
    debug?: {};
  } & {
    bookings: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      bookings: t.array(Booking_.Default),
      debug: t.type({}),
    }),
    t.type({
      bookings: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      bookings?: Array<Booking_.Default>;
      debug?: {};
    } & {
      bookings: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
