/*

undefined
Response schema for subscriptions-change-state

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as SubscriptionChangeState_ from 'maas-schemas-ts/core/components/subscriptionChangeState';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-change-state/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    changeState?: SubscriptionChangeState_.Default;
  } & {
    changeState:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      changeState: SubscriptionChangeState_.Default,
    }),
    t.type({
      changeState: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      changeState?: SubscriptionChangeState_.Default;
    } & {
      changeState:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
