/*

undefined
MaaS.fi routes-query response schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/routes/routes-query/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    plan: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    plan: t.union([t.type({}), t.null]),
  }),
  (
    x,
  ): x is t.Branded<
    {
      plan: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
