/*

undefined
An error that the service may send

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/error.json';

export type Default = t.Branded<
  {
    message: string;
    code: string;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    message: t.string,
    code: t.string,
  }),
  (
    x,
  ): x is t.Branded<
    {
      message: string;
      code: string;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
