/*

undefined
An error that the service may send

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/error.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    message?: string;
    code?: string;
  } & {
    message: {} | null;
    code: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      message: t.string,
      code: t.string,
    }),
    t.type({
      message: t.union([t.type({}), t.null]),
      code: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      message?: string;
      code?: string;
    } & {
      message: {} | null;
      code: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
