/*

undefined
MaaS user profiles as returned by our API

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as PointCost_ from 'maas-schemas-ts/core/components/point-cost';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as Address_ from 'maas-schemas-ts/core/components/address';
import * as Region_ from 'maas-schemas-ts/core/region';
import * as UnitsGeo_ from 'maas-schemas-ts/core/components/units-geo';
import * as Fare_ from 'maas-schemas-ts/core/components/fare';

export const schemaId = 'http://maasglobal.com/core/profile.json';
// SubscriptionInstance
// The purpose of this remains a mystery
export type SubscriptionInstance = t.Branded<
  {
    id?: number;
    name?: string;
    plan?: {
      id?: string;
    } & {
      id: unknown;
    };
    addons?: Array<string>;
    coupons?: Array<string>;
    wmpGrant?: number;
    level?: number;
    active?: boolean;
    pointCost?: PointCost_.Default;
    description?: string;
    availability?: number;
  } & {
    plan: unknown;
    addons: unknown;
    coupons: unknown;
    pointCost: unknown;
  },
  SubscriptionInstanceBrand
>;
export const SubscriptionInstance = t.brand(
  t.intersection([
    t.partial({
      id: t.number,
      name: t.string,
      plan: t.intersection([
        t.partial({
          id: t.string,
        }),
        t.type({
          id: t.unknown,
        }),
      ]),
      addons: t.array(t.string),
      coupons: t.array(t.string),
      wmpGrant: t.number,
      level: t.number,
      active: t.boolean,
      pointCost: PointCost_.Default,
      description: t.string,
      availability: t.number,
    }),
    t.type({
      plan: t.unknown,
      addons: t.unknown,
      coupons: t.unknown,
      pointCost: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id?: number;
      name?: string;
      plan?: {
        id?: string;
      } & {
        id: unknown;
      };
      addons?: Array<string>;
      coupons?: Array<string>;
      wmpGrant?: number;
      level?: number;
      active?: boolean;
      pointCost?: PointCost_.Default;
      description?: string;
      availability?: number;
    } & {
      plan: unknown;
      addons: unknown;
      coupons: unknown;
      pointCost: unknown;
    },
    SubscriptionInstanceBrand
  > => true,
  'SubscriptionInstance',
);
export interface SubscriptionInstanceBrand {
  readonly SubscriptionInstance: unique symbol;
}
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    id?: number;
    identityId?: Units_.IdentityId;
    phone?: Common_.Phone;
    email?: Common_.Email;
    firstName?: Common_.PersonalName;
    lastName?: Common_.PersonalName;
    city?: Address_.City;
    country?: Address_.Country;
    zipCode?: Address_.ZipCode;
    regionId?: string;
    region?: Region_.Default;
    profileImageUrl?: string;
    favoriteLocations?: Array<UnitsGeo_.Place>;
    paymentMethod?: {
      type?: string & ('unknown' | 'card' | 'stripe');
      valid?: boolean;
      maskedNumber?: string;
      issuer?: string;
      expiry?: Units_.Time;
    } & {
      type: unknown;
      valid: unknown;
    };
    subscription?: {};
    subscriptionInstance?: SubscriptionInstance;
    balance?: number;
    balances?: Array<Fare_.Default>;
    created?: Units_.Time;
    modified?: Units_.Time;
  } & {
    identityId: unknown;
    phone: unknown;
    favoriteLocations: unknown;
    balance: unknown;
    paymentMethod: unknown;
    subscriptionInstance: unknown;
    balances: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      id: t.number,
      identityId: Units_.IdentityId,
      phone: Common_.Phone,
      email: Common_.Email,
      firstName: Common_.PersonalName,
      lastName: Common_.PersonalName,
      city: Address_.City,
      country: Address_.Country,
      zipCode: Address_.ZipCode,
      regionId: t.string,
      region: Region_.Default,
      profileImageUrl: t.string,
      favoriteLocations: t.array(UnitsGeo_.Place),
      paymentMethod: t.intersection([
        t.partial({
          type: t.intersection([
            t.string,
            t.union([t.literal('unknown'), t.literal('card'), t.literal('stripe')]),
          ]),
          valid: t.boolean,
          maskedNumber: t.string,
          issuer: t.string,
          expiry: Units_.Time,
        }),
        t.type({
          type: t.unknown,
          valid: t.unknown,
        }),
      ]),
      subscription: t.type({}),
      subscriptionInstance: SubscriptionInstance,
      balance: t.number,
      balances: t.array(Fare_.Default),
      created: Units_.Time,
      modified: Units_.Time,
    }),
    t.type({
      identityId: t.unknown,
      phone: t.unknown,
      favoriteLocations: t.unknown,
      balance: t.unknown,
      paymentMethod: t.unknown,
      subscriptionInstance: t.unknown,
      balances: t.unknown,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id?: number;
      identityId?: Units_.IdentityId;
      phone?: Common_.Phone;
      email?: Common_.Email;
      firstName?: Common_.PersonalName;
      lastName?: Common_.PersonalName;
      city?: Address_.City;
      country?: Address_.Country;
      zipCode?: Address_.ZipCode;
      regionId?: string;
      region?: Region_.Default;
      profileImageUrl?: string;
      favoriteLocations?: Array<UnitsGeo_.Place>;
      paymentMethod?: {
        type?: string & ('unknown' | 'card' | 'stripe');
        valid?: boolean;
        maskedNumber?: string;
        issuer?: string;
        expiry?: Units_.Time;
      } & {
        type: unknown;
        valid: unknown;
      };
      subscription?: {};
      subscriptionInstance?: SubscriptionInstance;
      balance?: number;
      balances?: Array<Fare_.Default>;
      created?: Units_.Time;
      modified?: Units_.Time;
    } & {
      identityId: unknown;
      phone: unknown;
      favoriteLocations: unknown;
      balance: unknown;
      paymentMethod: unknown;
      subscriptionInstance: unknown;
      balances: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
