/*

undefined
MaaS user profiles as returned by our API

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as PointCost_ from 'maas-schemas-ts/core/components/point-cost';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as Address_ from 'maas-schemas-ts/core/components/address';
import * as Region_ from 'maas-schemas-ts/core/region';
import * as Place_ from 'maas-schemas-ts/core/components/place';
import * as Fare_ from 'maas-schemas-ts/core/components/fare';

export const schemaId = 'http://maasglobal.com/core/profile.json';
// SubscriptionInstance
// The purpose of this remains a mystery
export type SubscriptionInstance = t.Branded<
  {
    id?: number;
    name?: string;
    plan?: {
      id?: string;
    } & {
      id: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    };
    addons?: Array<string>;
    coupons?: Array<string>;
    wmpGrant?: number;
    level?: number;
    active?: boolean;
    pointCost?: PointCost_.Default;
    description?: string;
    availability?: number;
  } & {
    plan: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    addons: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    coupons: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    pointCost:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
  },
  SubscriptionInstanceBrand
>;
export const SubscriptionInstance = t.brand(
  t.intersection([
    t.partial({
      id: t.number,
      name: t.string,
      plan: t.intersection([
        t.partial({
          id: t.string,
        }),
        t.type({
          id: t.union([
            t.UnknownRecord,
            t.UnknownArray,
            t.string,
            t.boolean,
            t.number,
            t.null,
          ]),
        }),
      ]),
      addons: t.array(t.string),
      coupons: t.array(t.string),
      wmpGrant: t.number,
      level: t.number,
      active: t.boolean,
      pointCost: PointCost_.Default,
      description: t.string,
      availability: t.number,
    }),
    t.type({
      plan: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      addons: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      coupons: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      pointCost: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id?: number;
      name?: string;
      plan?: {
        id?: string;
      } & {
        id: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      };
      addons?: Array<string>;
      coupons?: Array<string>;
      wmpGrant?: number;
      level?: number;
      active?: boolean;
      pointCost?: PointCost_.Default;
      description?: string;
      availability?: number;
    } & {
      plan: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      addons: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      coupons:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      pointCost:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
    },
    SubscriptionInstanceBrand
  > => true,
  'SubscriptionInstance',
);
export interface SubscriptionInstanceBrand {
  readonly SubscriptionInstance: unique symbol;
}
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    id?: number;
    identityId?: Units_.IdentityId;
    phone?: Common_.Phone;
    email?: Common_.Email;
    firstName?: Common_.PersonalName;
    lastName?: Common_.PersonalName;
    city?: Address_.City;
    country?: Address_.Country;
    zipCode?: Address_.ZipCode;
    regionId?: string;
    region?: Region_.Default;
    profileImageUrl?: string;
    favoriteLocations?: Array<Place_.Default>;
    paymentMethod?: {
      type?: string & ('unknown' | 'card' | 'stripe');
      valid?: boolean;
      maskedNumber?: string;
      issuer?: string;
      expiry?: Units_.Time;
    } & {
      type: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      valid: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    };
    subscription?: {};
    subscriptionInstance?: SubscriptionInstance;
    balance?: number;
    balances?: Array<Fare_.Default>;
    created?: Units_.Time;
    modified?: Units_.Time;
  } & {
    identityId:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    phone: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    favoriteLocations:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    balance: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
    paymentMethod:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    subscriptionInstance:
      | Record<string, unknown>
      | Array<unknown>
      | string
      | boolean
      | number
      | null;
    balances: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      id: t.number,
      identityId: Units_.IdentityId,
      phone: Common_.Phone,
      email: Common_.Email,
      firstName: Common_.PersonalName,
      lastName: Common_.PersonalName,
      city: Address_.City,
      country: Address_.Country,
      zipCode: Address_.ZipCode,
      regionId: t.string,
      region: Region_.Default,
      profileImageUrl: t.string,
      favoriteLocations: t.array(Place_.Default),
      paymentMethod: t.intersection([
        t.partial({
          type: t.intersection([
            t.string,
            t.union([t.literal('unknown'), t.literal('card'), t.literal('stripe')]),
          ]),
          valid: t.boolean,
          maskedNumber: t.string,
          issuer: t.string,
          expiry: Units_.Time,
        }),
        t.type({
          type: t.union([
            t.UnknownRecord,
            t.UnknownArray,
            t.string,
            t.boolean,
            t.number,
            t.null,
          ]),
          valid: t.union([
            t.UnknownRecord,
            t.UnknownArray,
            t.string,
            t.boolean,
            t.number,
            t.null,
          ]),
        }),
      ]),
      subscription: t.type({}),
      subscriptionInstance: SubscriptionInstance,
      balance: t.number,
      balances: t.array(Fare_.Default),
      created: Units_.Time,
      modified: Units_.Time,
    }),
    t.type({
      identityId: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      phone: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      favoriteLocations: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      balance: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      paymentMethod: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      subscriptionInstance: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
      balances: t.union([
        t.UnknownRecord,
        t.UnknownArray,
        t.string,
        t.boolean,
        t.number,
        t.null,
      ]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id?: number;
      identityId?: Units_.IdentityId;
      phone?: Common_.Phone;
      email?: Common_.Email;
      firstName?: Common_.PersonalName;
      lastName?: Common_.PersonalName;
      city?: Address_.City;
      country?: Address_.Country;
      zipCode?: Address_.ZipCode;
      regionId?: string;
      region?: Region_.Default;
      profileImageUrl?: string;
      favoriteLocations?: Array<Place_.Default>;
      paymentMethod?: {
        type?: string & ('unknown' | 'card' | 'stripe');
        valid?: boolean;
        maskedNumber?: string;
        issuer?: string;
        expiry?: Units_.Time;
      } & {
        type: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
        valid:
          | Record<string, unknown>
          | Array<unknown>
          | string
          | boolean
          | number
          | null;
      };
      subscription?: {};
      subscriptionInstance?: SubscriptionInstance;
      balance?: number;
      balances?: Array<Fare_.Default>;
      created?: Units_.Time;
      modified?: Units_.Time;
    } & {
      identityId:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      phone: Record<string, unknown> | Array<unknown> | string | boolean | number | null;
      favoriteLocations:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      balance:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      paymentMethod:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      subscriptionInstance:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
      balances:
        | Record<string, unknown>
        | Array<unknown>
        | string
        | boolean
        | number
        | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
