/*

undefined
MaaS Zendesk push notification forwarder response schema.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/webhooks/zendesk-push-notification/response.json';

// Success
