/*

undefined
MaaS Zendesk push notification forwarder response schema.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/webhooks/zendesk-push-notification/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    results?: {
      successCount: {} | null;
      failureCount: {} | null;
    };
  } & {
    results: {} | null;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      results: t.type({
        successCount: t.union([t.type({}), t.null]),
        failureCount: t.union([t.type({}), t.null]),
      }),
    }),
    t.type({
      results: t.union([t.type({}), t.null]),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      results?: {
        successCount: {} | null;
        failureCount: {} | null;
      };
    } & {
      results: {} | null;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
