/*

undefined
Request schema for products-providers-options

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as UnitsGeo_ from 'src/core/components/units-geo';
import * as Units_ from 'src/core/components/units';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/products/products-providers-options/request.json';
// Payload
// The purpose of this remains a mystery
export type Payload = t.Branded<
  {
    lat: UnitsGeo_.RelaxedLatitude;
    lon: UnitsGeo_.RelaxedLongitude;
  },
  PayloadBrand
>;
export const Payload = t.brand(
  t.type({
    lat: UnitsGeo_.RelaxedLatitude,
    lon: UnitsGeo_.RelaxedLongitude,
  }),
  (
    x,
  ): x is t.Branded<
    {
      lat: UnitsGeo_.RelaxedLatitude;
      lon: UnitsGeo_.RelaxedLongitude;
    },
    PayloadBrand
  > => true,
  'Payload',
);
export interface PayloadBrand {
  readonly Payload: unique symbol;
}
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    identityId: Units_.IdentityId;
    payload: Payload;
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.exact(
    t.intersection([
      t.type({
        identityId: Units_.IdentityId,
        payload: Payload,
      }),
      t.partial({
        headers: ApiCommon_.Headers,
      }),
    ]),
  ),
  (
    x,
  ): x is t.Branded<
    {
      identityId: Units_.IdentityId;
      payload: Payload;
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
