/*

undefined
Response schema for canceling a booking through a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';

export const schemaId = 'http://maasglobal.com/tsp/bookings-cancel/response.json';

// Success
