/*

undefined
Request schema for update a state of a specific booking with a TSP ID from a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';

export const schemaId = 'http://maasglobal.com/tsp/bookings-update/request.json';

// Success
