/*

undefined
Response schema for reverse geocoding providers

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/maas-backend/provider/sms/response.json';

// Success
